name: PyTest
on: [push]

jobs:
  check-bats-version:
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: true
          workload_identity_provider: projects/570315564617/locations/global/workloadIdentityPools/my-github-actions/providers/scrobble-cloud-fn
          service_account: 'scrobble-cfunc@music-sql.iam.gserviceaccount.com'

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .github/requirements-github.txt
          python -m pip install -e . 
        # "pip install -e ." installs setup.py in working dir

      - name: Run flake8 # config file at tox.ini
        run:
          flake8

      - name: Run mypy # config file at pyproject.toml 
        run:
          mypy

      - name: Run tox (pytest)
        env: 
          GCLOUD_PROJECT: ${{ steps.auth.outputs.project_id }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |
          python -m pip install tox-gh-actions==2.9.1
          tox

      # - name: Run pytest
      #   env: 
      #     GCLOUD_PROJECT: ${{ steps.auth.outputs.project_id }}
      #     BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      #     LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
      #     LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      #   run:
      #     pytest

      - name: Completed running some echos
        run: echo "completed running my tests"

